package commands

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/Avdushin/secret/pkg/config"
	"github.com/spf13/cobra"
)

// @ init cmd
func InitCmd() *cobra.Command {
	var backend string

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Инициализирует проект для работы с секретами",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("Инициализация с бэкендом: %s\n", backend)

			//@ имя текущей папки как имя проекта по умолчанию
			projectDir, err := os.Getwd()
			if err != nil {
				fmt.Printf("Ошибка получения пути: %v\n", err)
				os.Exit(1)
			}
			defaultProjectName := filepath.Base(projectDir)

			//? pr name
			projectName := promptUser(
				fmt.Sprintf("Название проекта [%s]: ", defaultProjectName),
				defaultProjectName,
			)

			//@ Запрашиваем файлы/директории для шифрования
			fmt.Println("\nУкажите файлы или директории для шифрования (через запятую)")
			fmt.Printf("По умолчанию: %s\n", strings.Join(config.DefaultSecretFiles, ", "))
			filesInput := promptUser("Файлы/директории: ", "")

			var secretFiles []string
			if filesInput == "" {
				secretFiles = config.DefaultSecretFiles
			} else {
				secretFiles = strings.Split(filesInput, ",")
				for i := range secretFiles {
					secretFiles[i] = strings.TrimSpace(secretFiles[i])
				}
			}

			//@ Создаем GPG ключ
			timestamp := time.Now().Format("2006-01-02")
			keyName := fmt.Sprintf("%s Project Key (%s)", projectName, timestamp)
			keyEmail := fmt.Sprintf("project+%s@team.org", strings.ToLower(projectName))

			fmt.Printf("\nСоздаем GPG-ключ для проекта: %s\n", keyName)
			keyID, err := generateGPGKey(keyName, keyEmail, "Auto-generated by secret tool")
			if err != nil {
				fmt.Printf("Ошибка создания ключа: %v\n", err)
				os.Exit(1)
			}

			//@ Сохраняем конфиг
			cfg := &config.Config{
				Backend:     backend,
				GPGKey:      keyID,
				ProjectName: projectName,
				SecretFiles: secretFiles,
			}

			if err := config.SaveConfig(cfg); err != nil {
				fmt.Printf("Ошибка сохранения конфига: %v\n", err)
				os.Exit(1)
			}

			fmt.Printf("\n✅ Успешно! Ключ создан (ID: %s)\n", keyID)
			fmt.Printf("🔑 Для экспорта ключа выполните: secret export-key\n")
			fmt.Printf("🔒 Для шифрования файлов выполните: secret encrypt\n")
		},
	}

	cmd.Flags().StringVarP(&backend, "backend", "b", "gpg", "Бэкенд (gpg, vault, bitwarden)")
	return cmd
}

func promptUser(prompt, defaultValue string) string {
	reader := bufio.NewReader(os.Stdin)
	fmt.Print(prompt)
	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(input)

	if input == "" {
		return defaultValue
	}
	return input
}

func generateGPGKey(name, email, comment string) (string, error) {
	input := fmt.Sprintf("Key-Type: RSA\nKey-Length: 4096\nName-Real: %s\nName-Email: %s\nName-Comment: %s\nExpire-Date: 2y\n%%commit\n",
		name, email, comment)

	cmd := exec.Command("gpg", "--batch", "--gen-key")
	cmd.Stdin = strings.NewReader(input)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s: %v", string(output), err)
	}

	//? ID созданного ключа
	cmd = exec.Command("gpg", "--list-secret-keys", "--keyid-format", "LONG", email)
	output, err = cmd.CombinedOutput()
	if err != nil {
		return "", err
	}

	//? парсим ID ключа
	lines := strings.Split(string(output), "\n")
	for _, line := range lines {
		if strings.Contains(line, "sec") {
			parts := strings.Fields(line)
			if len(parts) > 2 {
				keyParts := strings.Split(parts[1], "/")
				if len(keyParts) > 1 {
					return keyParts[1], nil
				}
			}
		}
	}

	return "", fmt.Errorf("не удалось определить ID созданного ключа")
}
